# Basic `dependabot.yml` file with
# minimum configuration for three package managers

version: 2
updates:
  # Enable version updates for .NET Core projects
  - package-ecosystem: "nuget"
    directories:
      - "**/*"
    # Check the NuGet registry for updates every week (weekdays)
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "FluentAssertions"
        versions:
          - ">=8.0.0"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
